# Site settings
title: Kexin Li
email: kexin.li@ucl.ac.uk
cv: Kexin_LI_CV.pdf
description: 
baseurl: "" 
url: "http://kexinli.com" 
github_username:  kexinli
# whether to enable google resource  
google: true

# Build settings
markdown: kramdown
